from __future__ import annotations

from pathlib import Path
import numpy as np
import pandas as pd


class QuantStockScreener:
    """
    Buffett-side quantitative screening for candidate stocks.

    This module is NOT responsible for finding theme candidates.
    Input should already be a candidate pool generated by ThemeCandidateDiscovery.

    It computes:
    - market quality: Sharpe, Sortino, max drawdown, downside vol
    - valuation context: PB percentile
    - optional fundamental placeholders if daily_basic is available later

    Important:
    Missing moat research is NOT scored as zero.
    """

    def __init__(
        self,
        returns: pd.DataFrame,
        close: pd.DataFrame | None = None,
        pb_matrix: pd.DataFrame | None = None,
        risk_free_rate: float = 0.02,
        periods_per_year: int = 252,
    ):
        self.returns = returns.sort_index()
        self.close = close.sort_index() if close is not None else None
        self.pb_matrix = pb_matrix.sort_index() if pb_matrix is not None else None
        self.risk_free_rate = risk_free_rate
        self.periods_per_year = periods_per_year

    def _series_stats(self, r: pd.Series) -> dict:
        r = r.dropna()
        if len(r) < 120:
            return {
                "ann_return": np.nan,
                "ann_vol": np.nan,
                "sharpe": np.nan,
                "sortino": np.nan,
                "max_drawdown": np.nan,
                "downside_vol": np.nan,
                "n_obs": len(r),
            }

        wealth = (1 + r).cumprod()
        drawdown = wealth / wealth.cummax() - 1

        ann_return = wealth.iloc[-1] ** (self.periods_per_year / len(r)) - 1
        ann_vol = r.std() * np.sqrt(self.periods_per_year)

        rf_period = (1 + self.risk_free_rate) ** (1 / self.periods_per_year) - 1
        sharpe = ((r - rf_period).mean() / r.std()) * np.sqrt(self.periods_per_year) if r.std() else np.nan

        downside = r[r < 0]
        downside_vol = downside.std() * np.sqrt(self.periods_per_year) if len(downside) > 1 else np.nan
        sortino = (ann_return - self.risk_free_rate) / downside_vol if downside_vol and not np.isnan(downside_vol) else np.nan

        return {
            "ann_return": ann_return,
            "ann_vol": ann_vol,
            "sharpe": sharpe,
            "sortino": sortino,
            "max_drawdown": drawdown.min(),
            "downside_vol": downside_vol,
            "n_obs": len(r),
        }

    def _pb_percentile(self, code: str) -> float:
        if self.pb_matrix is None or code not in self.pb_matrix.columns:
            return np.nan

        s = self.pb_matrix[code].dropna()
        if len(s) < 120:
            return np.nan

        latest = s.iloc[-1]
        return float((s <= latest).mean())

    def screen(self, candidates: pd.DataFrame) -> pd.DataFrame:
        rows = []

        for _, row in candidates.iterrows():
            code = str(row["ts_code"])

            if code not in self.returns.columns:
                continue

            stats = self._series_stats(self.returns[code])
            stats["pb_percentile"] = self._pb_percentile(code)

            out = row.to_dict()
            out.update(stats)
            rows.append(out)

        df = pd.DataFrame(rows)

        if df.empty:
            return df

        # Conservative quant status. This is a gate label, not an investment decision.
        conditions = [
            df["sortino"].ge(0.8).fillna(False),
            df["max_drawdown"].ge(-0.65).fillna(False),
            df["n_obs"].ge(120).fillna(False),
        ]

        df["market_quality_pass"] = conditions[0] & conditions[1] & conditions[2]

        # PB percentile is contextual. Low percentile is useful; missing is UNKNOWN, not fail.
        df["valuation_context"] = np.select(
            [
                df["pb_percentile"].le(0.25),
                df["pb_percentile"].gt(0.25) & df["pb_percentile"].le(0.60),
                df["pb_percentile"].gt(0.60),
            ],
            [
                "LOW_PB_PERCENTILE",
                "MID_PB_PERCENTILE",
                "HIGH_PB_PERCENTILE",
            ],
            default="UNKNOWN",
        )

        # Do not force one total score.
        # We keep a soft ranking only for choosing which names to research first.
        df["research_priority_score"] = (
            df["theme_similarity"].fillna(0) * 0.40
            + df["sortino"].clip(-2, 3).fillna(0) / 3 * 0.35
            + df["sharpe"].clip(-2, 3).fillna(0) / 3 * 0.25
        )

        return df.sort_values(
            ["theme", "research_priority_score", "theme_similarity"],
            ascending=[True, False, False],
        ).reset_index(drop=True)
